spring.application.name=recicladora

spring.r2dbc.url=${DB_URL:r2dbc:mysql://localhost:3306/appdb}
spring.r2dbc.username=${DB_USER:app}
spring.r2dbc.password=${DB_PASSWORD:app123}

management.endpoints.web.exposure.include=health,info